### ISSUE TITLE
Incorrect `Content-Type` headers

### ISSUE THREAD

**Issue by RA80533** [codecov/uploader#145]
web.js uses incorrect headers to describe the `Content-Type` of the JSON payload.

**Comment by drazisil** [comment]
It you are referring to the PUT, the comment on https://github.com/codecov/uploader/blob/5856d15b622c529f8c0173fe0c45f8a599bee71b/src/helpers/web.js#L40 is the incorrect part. The PUT does send a gzip

**Comment by RA80533** [comment]
`Content-Type` specifies the original content type whereas `Content-Encoding` specifies the compression, etc.

`Content-Type` should be JSON.

**Comment by RA80533** [comment]
If the `Content-Type` is not being handled in a way that respects the actual content of the underlying content type of what’s being sent, do the back-end services just assume that the content being uploaded is JSON?

**Comment by drazisil** [comment]
Actually, I misspoke. The content is always text. What indicates to you that it is JSON?

**Comment by RA80533** [comment]
Simply based on that comment. If it's actually just a stream of text, [line 41](https://github.com/codecov/uploader/blob/5856d15b622c529f8c0173fe0c45f8a599bee71b/src/helpers/web.js#L41) and [69](https://github.com/codecov/uploader/blob/5856d15b622c529f8c0173fe0c45f8a599bee71b/src/helpers/web.js#L69) should be changed to `text/plain`.

**Comment by drazisil** [comment]
Got it. Thank for explaining, @RA80533 :)
