### ISSUE TITLE
codecov-linux.SHA256SUM is currently invalid

### ISSUE THREAD

**Issue by emteknetnz** [codecov/uploader#166]
codecov uploader for linux shasum failing - both on Travis CI - and have also replicated locally

```
shasum -a 256 -c codecov-linux.SHA256SUM
shasum: codecov: 
codecov: FAILED open or read
shasum: WARNING: 1 listed file could not be read
```

Originally setup using the instructions from https://docs.codecov.com/docs/codecov-uploader

Example of recent failure on travis:
https://travis-ci.com/github/silverstripe/silverstripe-assets/jobs/519946430#L1024

Travis config used for codecov:
https://github.com/silverstripe/silverstripe-travis-shared/blob/master/config/base.yml#L122

Looks like this has been failing for at least the last 3 hours (around 12:30am 29 June GMT), was working fine 18 hours ago (around 9:30am 28 June GMT)

Example of this working correctly 18 hours ago:
https://travis-ci.com/github/silverstripe/cwp-agencyextensions/jobs/519612481#L1098

**Comment by emteknetnz** [comment]
This error has now changed to 

```
codecov-linux: FAILED
shasum: WARNING: 1 computed checksum did NOT match
```

https://travis-ci.com/github/silverstripe/silverstripe-admin/jobs/520361354#L1077

**Comment by drazisil** [comment]
I'm on vacation and as such don't have access to the org. I'll take a look, also forwarding this to security@codecov.io.

Thanks for the heads-up, @emteknetnz

**Comment by montross50** [comment]
@emteknetnz There was an error with the filename that resulted in the error in your initial report. When rolling out that fix the shasum was mistakenly reported as the shasum for the previous version of the uploader. This was resolved around the same time as your update. If you could try again at your convenience, you should not see any more issues.

Running it locally I see
![image](https://user-images.githubusercontent.com/62939/124064395-448bdc00-d9fa-11eb-8eb5-2cd0b32059e9.png)
and
![image](https://user-images.githubusercontent.com/62939/124064507-887ee100-d9fa-11eb-90d7-cddbb9f613fb.png)

**Comment by emteknetnz** [comment]
Tested locally, works as it should.

Thanks for following this up, I'll close this one.
