### ISSUE TITLE
Upload from travis-ci.com fails to detect service

### ISSUE THREAD

**Issue by tagatac** [codecov/uploader#284]
**Describe the bug**
Following the instructions [here](https://docs.codecov.com/docs/codecov-uploader) in my travis-ci.com build, uploading the coverage report fails with an error about "Unable to detect service".

**To Reproduce**
1. Visit https://travis-ci.com/github/tagatac/bagoup/builds/234787055
2. Click on the arrow next to line 296.
3. Scroll down to line 337
4. See error "Unable to detect service, please specify manually."

**Expected behavior**
codecov uploads the coverage report without issue.

**Additional context**
Makefile target that generates this error at the commit that triggered the build referenced above: https://github.com/tagatac/bagoup/blob/14d7c0cb2349754a7f777f3abb50f90d43c9d313/Makefile#L36-L44

**Comment by tagatac** [comment]
Related: #252 and #23

**Comment by drazisil** [comment]
@drazisil-codecov will investigate tomorrow

In the meantime, can you check if the following envs appear in your build? https://github.com/codecov/uploader/blob/master/src/ci_providers/provider_travisci.ts#L4

**Comment by tagatac** [comment]
https://app.travis-ci.com/github/tagatac/bagoup/builds/234788670
```
echo $CI
true
echo $TRAVIS
true
echo $SHIPPABLE

```
Don't you want `SHIPPABLE` to be false? That's what the legacy script is looking for: https://github.com/codecov/codecov-bash/blob/1817ab23d6b35ff6596e48d15db366b71f17ada3/codecov#L568

**Comment by drazisil** [comment]
That's what I was wondering, but I was on mobile. At least we know the fix now.
