### ISSUE TITLE
the `-f` option seems to have stopped working in build `7865` (works in `6943`)

### ISSUE THREAD

**Issue by briantist** [codecov/uploader#303]
**Describe the bug**
My scheduled CI from 6 days ago succeeded: https://github.com/ansible-collections/community.hashi_vault/runs/3281498133?check_suite_focus=true#step:6:561
The scheduled CI from the next day, with no changes, failed: https://github.com/ansible-collections/community.hashi_vault/runs/3292087124?check_suite_focus=true#step:6:29

I am directly providing every file to be uploaded via `-f` options. This was working fine, now it can't find any files.

I tried this locally as well, downloading the latest version of the script, and I can't get it to recognize any files that way. Adding verbose, it looks like it's ignoring the `-f` option (though not completely, because I don't add it and it can't find any files, it says I should use `-f` to specify the files to upload).

**To Reproduce**
```
codecov -f path/to/file.xml
```

**Expected behavior**
Specified file(s) uploaded

**Screenshots**
![image](https://user-images.githubusercontent.com/1260690/129488481-53d1c502-4942-4d20-8477-5f9e20a6614e.png)

**Additional context**
The thing that puzzled me is that both before and after it broke, the version returned by the binary is `0.1.0`. Looking at your releases page it now seems like you release new versions without changing the version number? If so, that means I don't have any way of trying to download an older version to see if the behavior really changed. I also can't get the binary to show me a specific build/commit which would have also helped diagnose the difference.

A new build was released right around when the behavior seemingly changed. It contains 16 commits but I can't really tell which if any of them may have contributed to it:
https://github.com/codecov/uploader/compare/v0.1.0_7865...master

Edit: I see that there are tests for finding specific files with `-f`, and presumably those tests hadn't failed, so I'm not entirely sure what I'm seeing, I just know it was working 6+ days ago, and since then, it isn't :(

---

### confirmed
I put up a PR in my repo ( https://github.com/ansible-collections/community.hashi_vault/pull/129 ) that downloads the previous build direct from the github release, and with that previous release everything is working: https://github.com/ansible-collections/community.hashi_vault/runs/3334647366?check_suite_focus=true#step:6:362

I also confirmed this locally.

So, build 6943 works fine.
The build I get when downloading "latest" via https://uploader.codecov.io/latest/linux/codecov (which I presume is build 7865) is not working.

**Comment by drazisil** [comment]
@briantist Regarding older versions, if you drop `latest` from the URL, you can see all the versions available 

Regarding the `-f` flag, we'll take a look.

**Comment by briantist** [comment]
> @briantist Regarding older versions, if you drop `latest` from the URL, you can see all the versions available

I figured that out eventually, see https://github.com/ansible-collections/community.hashi_vault/pull/130 , but please consider actually including your build as part of the version number, and reporting it from the application itself. It would have been easier to troubleshoot if I could have clearly seen that the version changed based on the output.

> Regarding the `-f` flag, we'll take a look.

Thanks
