### ISSUE TITLE
Uploader v0.1.16 is broken on github-actions: No coverage files located

### ISSUE THREAD

**Issue by viceice** [codecov/uploader#614]
**Describe the bug**
Since v0.1.16 the uploader no longer finds the coverage files: 

- working v0.1.15 https://github.com/renovatebot/renovate/runs/5058338188?check_suite_focus=true
- failing v0.1.16 https://github.com/renovatebot/renovate/runs/5064757085?check_suite_focus=true

**To Reproduce**
1. use latest codecov-action
2. try to upload coverage

**Expected behavior**
Coverage uploads should simply work

**Screenshots**
no, see links above

**Additional context**

- https://app.codecov.io/gh/renovatebot/renovate/commits?page=1

/cc @rarkins

**Comment by Flamefire** [comment]
Having the same issue. Looking through the changes I suspect this: https://github.com/codecov/uploader/commit/ea1c97096ed2d76b9b1ce9d05982c0092be5bbb2#diff-ffd5012178bb277cea8ca8ffeea7ea4ccfc993570bd350f4a8a38c045422b271R340

For us the file `coverage.info` is excluded.

Also some (at least) debug logging around this https://github.com/codecov/uploader/blob/7a9a54e245e629c9a1c8891352cf6941ae4d2496/src/index.ts#L212 would be nice so one can see the picked up and the block-listed files, at least when running with `--verbose`

**Comment by dlech** [comment]
Broke us too: https://github.com/dlech/SshAgentLib/runs/5072773528?check_suite_focus=true#step:6:24

**Comment by viceice** [comment]
Workaround:
 https://github.com/renovatebot/renovate/pull/14007

**Comment by Flamefire** [comment]
Note that passing `--file path/to/coverage.info` also works, especially in combination with `-X search`

**Comment by fingolfin** [comment]
Same issue: we had a coverage file name `gap-coverage.json`, which isn't uploaded anymore. Adding it explicitly to the `files` list triggered the message: @Flamefire reported above:
```
[2022-02-05T16:51:19.916Z] ['info'] Warning: Some files passed via the -f flag would normally be excluded from search.
```
So it seems some block rule matches, but I see nothing obviously doing so in the array at https://github.com/codecov/uploader/blob/main/src/helpers/files.ts#L46 (tath

BTW, I also renamed that file to `coverage-final.json` which is explicitly in `coverageFilePatterns()` and it still was not picked up. So really, there seems to be a regression in the code which excludes files from upload

**Comment by fingolfin** [comment]
I wonder if PR #577 is involved

**Comment by Flamefire** [comment]
> I wonder if PR #577 is involved

I would say yes as the comment from @mitchell-codecov says: https://github.com/codecov/uploader/pull/577/files#r787846281

The blocklist is "globstared": https://github.com/codecov/uploader/blob/7a9a54e245e629c9a1c8891352cf6941ae4d2496/src/helpers/files.ts#L336

But `contains` is used: https://github.com/codecov/uploader/blob/7a9a54e245e629c9a1c8891352cf6941ae4d2496/src/helpers/files.ts#L340
