### ISSUE TITLE
Uploader validation failed due to keybase.io outage

### ISSUE THREAD

**Issue by guibirow** [codecov/uploader#903]
**Describe the bug**
We use [Codecov CircleCI Orb](https://circleci.com/developer/orbs/orb/codecov/codecov) to upload our artifacts using the embeded uploader.
The uploader validation fails because it has a dependency on *keybase.io* which is currently down.

**To Reproduce**
1. Create a CircleCI pipeline with  [Codecov CircleCI Orb](https://circleci.com/developer/orbs/orb/codecov/codecov)
2. Run the pipeline cotaining the step that uses the uploader
3. Pipeline will fail because uploader file can't be validated

**Expected behavior**
Downloading the Uploader should succeed and not depend on external services.

**Screenshots**
CircleCI error
![image](https://user-images.githubusercontent.com/943026/195143291-48925452-8b4d-442e-8e55-c083129c7324.png)

keybase.io SSL error
<img width="798" alt="image" src="https://user-images.githubusercontent.com/943026/195143615-c5a98cae-c1b5-4f8d-9c08-c1be8f99a61e.png">

**Additional context**

```
#!/bin/bash -eo pipefail
source $BASH_ENV
curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import # One-time step
curl -Os "https://uploader.codecov.io/latest/${os}/${filename}.SHA256SUM"
curl -Os "https://uploader.codecov.io/latest/${os}/${filename}.SHA256SUM.sig"
gpgv $filename.SHA256SUM.sig $filename.SHA256SUM
shasum -a 256 -c $filename.SHA256SUM || sha256sum -c $filename.SHA256SUM

------ Output

gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/trustedkeys.gpg' created
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to keybase.io:443 
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0

Exited with code exit status 2
CircleCI received exit code 2

```

**Comment by Jaryt** [comment]
@guibirow Was also running into this but kept trying and looks like they've just recovered.
